### ISSUE TITLE
Queue is missing health probes

### ISSUE THREAD

**Issue by Slav4ik** [langchain-ai/helm#134]
Our k8s ecosystem requires all deployments (not jobs) to have liveness/readiness/startup probes.

langsmith-queue is missing them.

**Comment by langchain-infra** [comment]
Hi, I actually have just merged in an update that adds this!

**Comment by Slav4ik** [comment]
Thank you very much, I must admit I didnt expect it so fast

It seems that a semicolon is missing in this [line](https://github.com/langchain-ai/helm/blob/58c23348f163564ed1db961cac30a0ad4fb5a5e4/charts/langsmith/templates/frontend/config-map.yaml#L25)
And this config was only changed for subdomain variant and not the default.

**Comment by langchain-infra** [comment]
Great catch and apologies. That is fixed here: https://github.com/langchain-ai/helm/pull/135
